
CREATE TABLE TB_TIPO_PARTICIPANTE
( 
  ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TB_TIPO_PARTICIPANTE PRIMARY KEY,
  TIPO_PARTICIPANTE VARCHAR(50) not null
)

INSERT INTO TB_TIPO_PARTICIPANTE VALUES ('Professor')
INSERT INTO TB_TIPO_PARTICIPANTE VALUES ('Aluno')

GO
CREATE TABLE TB_PARTICIPANTE
(
 ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TB_PARTICIPANTE PRIMARY KEY,
 ID_TIPO_PARTICIPANTE INT NOT NULL CONSTRAINT FK_PART_TB_TIPO_PARTICIPANTE FOREIGN KEY REFERENCES TB_TIPO_PARTICIPANTE(ID),
 TX_NOME VARCHAR (50) NOT NULL,
 TX_CPF VARCHAR(11) NOT NULL,
 TX_EMAIL VARCHAR(50) NOT NULL
)

go
INSERT INTO TB_PARTICIPANTE VALUES (1, 'Professor da Silva', '123', 'psilva@gmail.com');
INSERT INTO TB_PARTICIPANTE VALUES (2, 'Aluno Borges', '321', 'aborges@gmail.com');

go
CREATE TABLE TB_TIPO_COMPROMISSO
(ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TB_TIPO_COMPROMISSO PRIMARY KEY,
TX_DESCRICAO VARCHAR (50) NOT NULL)
go
INSERT INTO TB_TIPO_COMPROMISSO VALUES ('Aula')
INSERT INTO TB_TIPO_COMPROMISSO VALUES ('Palestra')
INSERT INTO TB_TIPO_COMPROMISSO VALUES ('Visita Tecnica')
INSERT INTO TB_TIPO_COMPROMISSO VALUES ('Feira')
INSERT INTO TB_TIPO_COMPROMISSO VALUES ('Congresso')
INSERT INTO TB_TIPO_COMPROMISSO VALUES ('TCC')
INSERT INTO TB_TIPO_COMPROMISSO VALUES ('Conselho')
INSERT INTO TB_TIPO_COMPROMISSO VALUES ('Planejamento')
INSERT INTO TB_TIPO_COMPROMISSO VALUES ('Reuniao Pedagogica')
INSERT INTO TB_TIPO_COMPROMISSO VALUES ('Reuniao de Pais')
INSERT INTO TB_TIPO_COMPROMISSO VALUES ('Festividade')
GO
CREATE TABLE TB_COMPROMISSO
(ID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_TB_COMPROMISSO PRIMARY KEY,
ID_TIPO_COMPROMISSO INT NOT NULL CONSTRAINT FK_COMP_TB_TIPO_COMPROMISSO FOREIGN KEY REFERENCES
TB_TIPO_COMPROMISSO(ID),
TX_DESCRICAO VARCHAR(50) not null,
TX_LOCALIZACAO VARCHAR(500) not null,
DT_INICIO DATETIME NOT NULL,
DT_TERMINO DATETIME NOT NULL,
FL_VISIVEL BIT CONSTRAINT DF_FL_VISIVEL DEFAULT 1)
INSERT INTO TB_COMPROMISSO (ID_TIPO_COMPROMISSO, TX_DESCRICAO, TX_LOCALIZACAO, DT_INICIO, DT_TERMINO,
FL_VISIVEL)
VALUES (1, 'Aula 01/07/2021', 'Aula Remota Teams', '2021-07-01', '2021-07-01', 1)
GO --Não usaremos essas tabelas, mas fica como exemplo de vinculação do compromisso com os participantes
CREATE TABLE TB_COMPROMISSO_PARTICIPANTE
( ID_COMPROMISSO INT NOT NULL CONSTRAINT FK_CP_COMPROMISSSO FOREIGN KEY REFERENCES
TB_COMPROMISSO(ID),
ID_PARTICIPANTE INT NOT NULL CONSTRAINT FK_CP_PARTICIPANTE FOREIGN KEY REFERENCES
TB_PARTICIPANTE(ID))
GO
CREATE TABLE TB_COMPROMISSO_IMAGENS
(ID int IDENTITY(1,1) NOT NULL,
ID_COMPROMISSO int NOT NULL CONSTRAINT FK_IM_COMPROMISSO FOREIGN KEY REFERENCES
TB_COMPROMISSO(ID),
VB_CONTEUDO_FOTO varbinary(max) NULL,
TX_CAMINHO_FOTO varchar(max) NULL,
TX_OBSERVACOES varchar(500) NULL)